In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.impute import SimpleImputer  #for simple numerical value
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [15]:
df = pd.read_csv("/content/covid_toy.csv")

In [4]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [5]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [6]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [7]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [16]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train ,y_test = train_test_split(df.drop(columns =['has_covid']),df['has_covid'] , test_size = 0.2)

In [10]:
#normal way
X_train

age  gender  fever   cough       city
45   72    Male   99.0    Mild  Bangalore
69   73  Female  103.0    Mild      Delhi
24   13  Female  100.0  Strong    Kolkata
87   47    Male  101.0  Strong  Bangalore
85   16  Female  103.0    Mild  Bangalore
..  ...     ...    ...     ...        ...
14   51    Male  104.0    Mild  Bangalore
65   69  Female  102.0    Mild  Bangalore
15   70    Male  103.0  Strong    Kolkata
9    64  Female  101.0    Mild      Delhi
91   38    Male    NaN    Mild      Delhi

[80 rows x 5 columns]

In [17]:
from sklearn.impute import SimpleImputer

xl = SimpleImputer()
#this is used for removing null values from the data
# Fix: use double brackets to keep it 2D
X_train_fever = xl.fit_transform(X_train[['fever']])
X_test_fever = xl.transform(X_test[['fever']])


In [21]:
ol = OrdinalEncoder(categories = [['Mild','Strong']])
X_train_cough = ol.fit_transform(X_train[['cough']])
X_test_cough = ol.transform(X_test[['cough']])
X_train_cough

array([[1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],

In [22]:
X_train_fever

array([[104.        ],
       [102.        ],
       [104.        ],
       [104.        ],
       [ 98.        ],
       [100.97260274],
       [102.        ],
       [104.        ],
       [ 99.        ],
       [100.        ],
       [100.97260274],
       [ 99.        ],
       [101.        ],
       [101.        ],
       [104.        ],
       [ 99.        ],
       [102.        ],
       [ 98.        ],
       [101.        ],
       [100.        ],
       [100.        ],
       [100.        ],
       [100.        ],
       [104.        ],
       [103.        ],
       [100.97260274],
       [100.        ],
       [101.        ],
       [101.        ],
       [ 98.        ],
       [101.        ],
       [ 98.        ],
       [104.        ],
       [103.        ],
       [ 98.        ],
       [100.        ],
       [100.97260274],
       [100.        ],
       [ 98.        ],
       [103.        ],
       [100.97260274],
       [101.        ],
       [ 99.        ],
       [101

In [23]:
X_train_fever.shape , X_train_cough.shape

((80, 1), (80, 1))

In [26]:
#apply onehotencoding on city , gender
ohe = OneHotEncoder(drop = 'first' , sparse_output=False)
X_train_gender_city = ohe.fit_transform(X_train[['gender' , 'city']])
X_test_gender_city = ohe.fit_transform(X_test[['gender' ,'city']])
X_train_gender_city

array([[0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],


In [27]:
#Extracting age
X_train_age = X_train.drop(columns=['gender' ,'fever','cough','city']).values

In [28]:
X_test_age = X_test.drop(columns=['gender' ,'fever','cough','city']).values

In [29]:
X_train_age.shape

(80, 1)

In [31]:
X_train_transformed = np.concatenate((X_train_age , X_train_fever , X_train_cough , X_train_gender_city) , axis = 1)
X_test_transformed = np.concatenate((X_train_age , X_train_fever , X_train_cough , X_train_gender_city) , axis = 1)

In [33]:
X_train_transformed

array([[ 75.        , 104.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 33.        , 102.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 44.        , 104.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ],
       [ 56.        , 104.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 10.        ,  98.        ,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 38.        , 100.97260274,   0.        ,   1.        ,
          1.        ,   0.        ,   0.        ],
       [ 82.        , 102.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 54.        , 104.        ,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 65.        ,  99.        ,   0.        ,   1.        ,
          1.    

In [34]:
#USING COLUMN TRANSFORM
from sklearn.compose import ColumnTransformer
transformer = ColumnTransformer(transformers =[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories = [['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output = False , drop = 'first') , ['gender' , 'city'])
] , remainder = 'passthrough')

In [35]:
transformer.fit_transform(X_train)

array([[104.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  75.        ],
       [102.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  33.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  44.        ],
       [104.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  56.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  10.        ],
       [100.97260274,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  38.        ],
       [102.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  82.        ],
       [104.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  54.        ],
       [ 99.        ,   0.        ,   1.        ,   1.        ,
          0.    

In [36]:
transformer.fit_transform(X_train).shape

(80, 7)