In [1]:
import numpy as np
from sklearn.datasets import load_diabetes

In [2]:
X , y = load_diabetes(return_X_y = True)

In [3]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [4]:
X.shape

(442, 10)

In [5]:
y.shape

(442,)

In [7]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

In [8]:
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size = 0.2 , random_state = 42)

In [9]:
X_train.shape

(353, 10)

In [10]:
y_train.shape

(353,)

In [11]:
lr = LinearRegression()

In [12]:
lr.fit(X_train , y_train)

LinearRegression()

In [13]:
y_pred = lr.predict(X_test)

In [14]:
print("r2_score" , r2_score(y_test , y_pred))

r2_score 0.4526027629719195


In [15]:
lr.coef_

array([  37.90402135, -241.96436231,  542.42875852,  347.70384391,
       -931.48884588,  518.06227698,  163.41998299,  275.31790158,
        736.1988589 ,   48.67065743])

In [16]:
lr.intercept_

np.float64(151.34560453985995)

In [28]:
class myLR:
  def __init__(self):
    self.coef_ = None
    self.intercept_ = None
  def fit(self, X_train , y_train):
    #adding the additional column inside X_train containing all 1
    # np.insert(in which matrix , which index , what change , which axis)
    X_train = np.insert(X_train , 0 , 1 , axis = 1)

    #calculate the coffieceints
    betas = np.linalg.inv(np.dot(X_train.T , X_train)).dot(X_train.T).dot(y_train)
    self.intercept_ = betas[0]
    self.coef_ = betas[1:]
    return self.intercept_ , self.coef_
  def predict(self , X_test):
    return np.dot(X_test , self.coef_)+self.intercept_

In [29]:
lr1 = myLR()

In [30]:
lr1.fit(X_train , y_train)

(np.float64(151.34560453986003),
 array([  37.90402135, -241.96436231,  542.42875852,  347.70384391,
        -931.48884588,  518.06227698,  163.41998299,  275.31790158,
         736.1988589 ,   48.67065743]))

In [31]:
y_pred = lr1.predict(X_test)

array([139.5475584 , 179.51720835, 134.03875572, 291.41702925,
       123.78965872,  92.1723465 , 258.23238899, 181.33732057,
        90.22411311, 108.63375858,  94.13865744, 168.43486358,
        53.5047888 , 206.63081659, 100.12925869, 130.66657085,
       219.53071499, 250.7803234 , 196.3688346 , 218.57511815,
       207.35050182,  88.48340941,  70.43285917, 188.95914235,
       154.8868162 , 159.36170122, 188.31263363, 180.39094033,
        47.99046561, 108.97453871, 174.77897633,  86.36406656,
       132.95761215, 184.53819483, 173.83220911, 190.35858492,
       124.4156176 , 119.65110656, 147.95168682,  59.05405241,
        71.62331856, 107.68284704, 165.45365458, 155.00975931,
       171.04799096,  61.45761356,  71.66672581, 114.96732206,
        51.57975523, 167.57599528, 152.52291955,  62.95568515,
       103.49741722, 109.20751489, 175.64118426, 154.60296242,
        94.41704366, 210.74209145, 120.2566205 ,  77.61585399,
       187.93203995, 206.49337474, 140.63167076, 105.59

In [32]:
print(r2_score(y_test , y_pred))

0.4526027629719195
